apiVersion: v1
kind: Pod
metadata:
  name: homework
  namespace: homework
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 8000
      volumeMounts:
      - name: workdir
        mountPath: "/homework"
      lifecycle:
        preStop:
          exec:
            command:
              - rm
              - "-f"
              - "/homework/index.html"
  initContainers:
    - name: install
      image: busybox:1.28
      command:
      - wget
      - "-O"
      - "/init/index.html"
      - http://info.cern.ch
      volumeMounts:
      - name: workdir
        mountPath: "/init"
  dnsPolicy: Default
  volumes:
  - name: workdir
    emptyDir: {}

